library(shiny)

source("helper.R")

shinyUI <- fluidPage(
  
  titlePanel("Birds of Panchayats in Kerala. Open Links in INCOGNITO Mode"),
  
  sidebarPanel(
    
    helpText(h4("Select the region which you would like to obtain bar charts")),
    selectInput('region', 'Regions', choices = c("All", sort(unique(ebd$REGION))), selected = 'All')
  ),
  
  mainPanel(
    tabsetPanel(
      tabPanel("Bar Chart Links", dataTableOutput('barchartlinks')),
      tabPanel("Locations", dataTableOutput('localities')),
      tabPanel("Map", 
               fluidRow(
                   column (3, 
                           textOutput ("Map of the polygon")        
                   ),
                   br(),
                   column (1, 
                           plotOutput('displaymap')))),      
      tabPanel("About", 
               br(), h1("eBird Bar Charts for Panchayats of Kerala"), 
               br(), p("This app helps in combining hotspots and personal locations into single link to be opened in eBird."),
               br(), p("All data is hosted in www.ebird.org/india  and has been generated by the large community of bird-watchers through casual birding and systematic surveys. "), 
               br(), p("This app only helps in combining hotspots and personal locations into single link to be opened in eBird."),
               br(), p("We recommend you open in incognito mode to view data from personal locations as well."),
               br(), p("Last data update: Through September 2019:"),
               br(), p("Fixed memory issues and speed of load: 5 November 2019:"),
               br(), p("Comments, suggestions and criticisms. Contact Praveen J. Email: paintedstork@gmail.com")
      )
    )
  )
)

options(shiny.maxRequestSize=30*1024^2) 

shinyServer <- function(session, input, output) {
  
  output$barchartlinks <-   renderDataTable ( {
    print("Starting Barchart links",)
    processMap (input$region) %>% 
        generateBarChartLinks() 
  }, escape = FALSE, options = list(
      lengthMenu = list(c(5, 20, 50, 100, 300, 500, -1), c('5', '20', '50', '100', '300', '500', 'All')),
      pageLength = 500))
  
  output$localities <-   renderDataTable ( {
    processMap (input$region) %>% 
        generateLocalities() 
  }, escape = FALSE, options = list(
      lengthMenu = list(c(5, 20, 50, 100, 300, 500, -1), c('5', '20', '50', '100', '300', '500', 'All')),
      pageLength = 500) )
  
  output$displaymap <-   renderPlot ( {
    map %>% 
      plotDisplayMap(input$region, processMap (input$region) %>% generateLocalities())
  }, height = 700, width = 700)  
}

shinyApp(ui = shinyUI, server = shinyServer)